export const VISIBILITY = Object.freeze({
  PUBLIC: "PUBLIC",
  PUBLIC_REDACTED: "PUBLIC_REDACTED",
  DRAFT: "DRAFT",
  INTERNAL_ONLY: "INTERNAL_ONLY",
  HIDDEN: "HIDDEN",
});

export const CLASSIFICATION = Object.freeze({
  REAL_PROJECT: "REAL_PROJECT",
  REAL_BUSINESS_WORK: "REAL_BUSINESS_WORK",
  INTERNAL_PRODUCT: "INTERNAL_PRODUCT",
  INTERNAL_AUTOMATION: "INTERNAL_AUTOMATION",
  INTERNAL_TOOL: "INTERNAL_TOOL",
  EXPERIMENT: "EXPERIMENT",
  SIMULATION: "SIMULATION",
  CREATIVE_WORK: "CREATIVE_WORK",
});

export const DELIVERY_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  SHIPPED: "SHIPPED",
  VALIDATED_PROTOTYPE: "VALIDATED_PROTOTYPE",
  PROTOTYPE: "PROTOTYPE",
  EXPERIMENT: "EXPERIMENT",
  SIMULATION: "SIMULATION",
  ARCHIVED: "ARCHIVED",
});

export const CONTENT_STATUS = Object.freeze({
  READY: "READY",
  PARTIAL: "PARTIAL",
  NEEDS_CONTENT: "NEEDS_CONTENT",
  NEEDS_EVIDENCE: "NEEDS_EVIDENCE",
  NEEDS_REDACTION: "NEEDS_REDACTION",
  DRAFT: "DRAFT",
});

export const EVIDENCE_STATUS = Object.freeze({
  CONFIRMED: "CONFIRMED",
  USER_VERIFIED: "USER_VERIFIED",
  NEEDS_VERIFICATION: "NEEDS_VERIFICATION",
});

export const EVIDENCE_TYPE = Object.freeze({
  SCREENSHOT: "SCREENSHOT",
  DECK: "DECK",
  LIVE_DEMO: "LIVE_DEMO",
  VIDEO: "VIDEO",
  PROCESS_DIAGRAM: "PROCESS_DIAGRAM",
  DOCUMENT: "DOCUMENT",
});

export const EVIDENCE_ORIGIN = Object.freeze({
  REAL_SCREENSHOT: "REAL_SCREENSHOT",
  RECONSTRUCTED_PROCESS_DIAGRAM: "RECONSTRUCTED_PROCESS_DIAGRAM",
  DEMO_DATA: "DEMO_DATA",
  PUBLIC_ARTIFACT: "PUBLIC_ARTIFACT",
});

export const REDACTION_STATUS = Object.freeze({
  NOT_REQUIRED: "NOT_REQUIRED",
  REDACTED_APPROVED: "REDACTED_APPROVED",
  REDACTION_REQUIRED: "REDACTION_REQUIRED",
  RAW_INTERNAL: "RAW_INTERNAL",
});

export const ROLE_LENS_IDS = Object.freeze([
  "aiProduct",
  "productOps",
  "projectOps",
  "growth",
  "aiNative",
]);

export const PUBLIC_VISIBILITIES = Object.freeze([
  VISIBILITY.PUBLIC,
  VISIBILITY.PUBLIC_REDACTED,
]);

export const PUBLIC_READY_STATUSES = Object.freeze([
  CONTENT_STATUS.READY,
  CONTENT_STATUS.PARTIAL,
  CONTENT_STATUS.NEEDS_EVIDENCE,
]);
